[ejs.app]
loading = "Loading in progress..."
language = "English (US)"

[ejs.landing]
shopButton = "PlayClan Shop"
updateAvailable = "Update available"
shopOpen = "OPEN SHOP"
playername = "Playername"
edit = "Edit"
settings = "Settings"
server = "SERVER"
offline = "OFFLINE"
playclanStatus = "PLAYCLAN SERVERS"
playclanServers = "SERVER STATUSES"
news = "NEWS"
start = "START"
notSelected = "Server not selected"
wait = "Please wait..."
newsLoading = "Loading news..."
newsFailed = "Failed to load news"
retry = "Retry"
noNews = "No news available"

[ejs.login]
cancel = "Cancel"
title = "MINECRAFT LOGIN"
invalidValue = "Invalid value"
email = "EMAIL OR PLAYERNAME"
password = "PASSWORD"
required = "Required"
forgotPassword = "Forgot password?"
rememberMe = "Remember me?"
login = "LOGIN"
needAccount = "Need an account?"
privacy = "Your password is sent directly to Mojang and is never stored."

[ejs.loginOptions]
title = "Login"
playclan = "PlayClan account"
microsoft = "Microsoft account"
mojang = "Mojang account"
cancel = "Cancel"

[ejs.overlay]
serverHeader = "Available versions"
accountHeader = "Select account"
cancel = "Cancel"
select = "Select"

[ejs.settings.navbar]
header = "Settings"
account = "Account"
minecraft = "Minecraft"
mods = "Mods"
java = "Java"
launcher = "Launcher"
about = "About"
updates = "Updates"
done = "Done"

[ejs.settings.account]
header = "Account settings"
desc = "Add a new account or manage existing ones."
playclan = "PlayClan"
playclanAdd = "+ Add PlayClan account"
microsoft = "Microsoft"
microsoftAdd = "+ Add Microsoft account"
mojang = "Mojang"
mojangAdd = "+ Add Mojang account"

[ejs.settings.minecraft]
header = "Minecraft settings"
desc = "Settings related to starting the game."
resolution = "Game resolution"
autoconnect = "Connect to the server automatically on startup."
detach = "Launch game process detached from launcher."
detachDesc = "If the game is not detached, closing the launcher will also close the game."

[ejs.settings.mods]
header = "Mod settings"
desc = "Enable or disable mods."
change = "Change"
required = "Required mods"
optional = "Optional mods"
mods = "Mods"
add = "+ Add mods"
refresh = "(F5 to refresh)"
shaders = "Shaderpacks"
shadersDesc = "Enable or disable shaders. Please note, shaders will only run smoothly on powerful setups. You may add custom packs here."
shadersSelect = "Select shaderpack"

[ejs.settings.java]
header = "Java settings"
desc = "Manage the Java configuration (advanced)."
change = "Change"
memory = "Memory"
memoryMax = "Maximum RAM"
memoryMin = "Minimum RAM"
memoryDesc = "The recommended minimum RAM is 3 gigabytes. Setting the minimum and maximum values to the same value may reduce lag."
memoryTotal = "Total"
memoryAvaliable = "Available"
executable = "Java executable"
select = "Select file"
execDesc = "The Java executable is validated before game launch."
execPath = "The path should end with:"
other = "Additional JVM Options"
otherDesc = "Options to be provided to the JVM at runtime. <em>-Xms</em> and <em>-Xmx</em> should not be included."

[ejs.settings.launcher]
header = "Launcher settings"
desc = "Manage the launcher configuration"
beta = "Allow beta updates"
betaDesc = "Beta include new features which may have not been fully tested or integrated.<br>This will always be true if you are using a beta version."
discord = "Allow Discord Rich Presence"
discordDesc = "Discord Rich Presence allows you to show what you are doing in Minecraft on your Discord profile."
hide = "Auto hide launcher"
hideDesc = "Automatically hide the launcher when the game starts."
ipProtection = "Allow automatic IP protection"
ipProtectionDesc = "Your account will be automatically protected to your IP address when you launch Minecraft. <small>(This feature only works if you start Minecraft with your PlayClan account.)</small>"
folder = "Data folder"
folderChoose = "Choose folder"
folderDesc = "All game files and local Java installations are stored in this folder.<br>Screenshots and world saves are stored in the appropriate server configuration folder."
language = "Application language"
languageDesc = "The language of the launcher."
languageSelect = "Select language"

[ejs.settings.about]
header = "About"
desc = "View current version information and changelog."
title = "PlayClan Launcher"
source = "Source code (GitHub)"
originalSource = "Original source code (GitHub)"
help = "Request help"
devtools = "DevTools Console"
changelog = "Changelog"
changes = "Changes"
noChanges = "No changes"
changesGithub = "View changes on GitHub"

[ejs.settings.updates]
header = "Launcher Updates"
desc = "Download, install and review launcher updates."
uptodate = "Launcher is up to date"
search = "Check for updates"
whatsnew = "What's new?"
changes = "Update changelog"
noChanges = "Nincs változtatás"

[ejs.waiting]
microsoft = "Waiting for Microsoft's response..."
playclan = "Waiting for PlayClan's response..."

[ejs.welcome]
header = "WELCOME TO PLAYCLAN LAUNCHER!"
desc = "Our goal with this launcher is to provide a better gaming experience to everyone who uses it."
cta = "You are just a few clicks away from discovery!"
button = "COUNTINUE"

[js.landing]
pleaseWait = "Loading..."
errorStartupTitle = "Startup error"
errorConsole = "See the console (CTRL + Shift + i) for more errors."
noAccount = "No account selected"
noServer = "No server selected"
loading = "Loading..."
server = "SERVER"
offline = "OFFLINE"
players = "PLAYERS"
checkingJava = "Checking Java..."
javaNotFoundTitle = "No compatible<br>Java installation found"
javaNotFoundContent1 = "A 64-bit Java"
javaNotFoundContent2 = "is required to join PlayClan. Would you like us to install it?"
javaNotFoundButton = "Install Java"
javaNotFoundButtonAlt = "Manual installation"
downloadJava = "Downloading Java..."
errorJavaTitle = "Error while downloading Java"
javaManualTitle = "Java is required<br>to start"
javaManualContent1 = "A valid x64 Java"
javaManualContent2 = "installation is required to start it.<br><br>Please see the <a href=\"https://github.com/PlayClan/PCLauncher/wiki/Java-Management#manually-installing-a-valid-version-of-java\">Java user guide</a> to install Java manually."
javaManualButton = "I understood"
javaManualButtonAlt = "Back"
extractingJava = "Extracting Java..."
javaComplete = "Java installed!"
loadingInfo = "Loading information..."
fatalErrorTitle = "Fatal error"
verifying = "Please wait..."
validating = "Validating files..."
downloading = "Downloading files..."
errorValidate = "Error while validating files"
errorDownload = "Error while downloading files"
finalizing = "Finalizing..."
launching = "Launching..."
errorLaunch = "Error while launching"
errorLaunchWrapper = "The main file, LaunchWrapper, failed to download properly. As a result, the game cannot launch.<br><br>To fix this issue, temporarily turn off your antivirus software and launch the game again.<br><br>If you have time, please <a href=\"https://dc.playclan.hu/\">submit an issue</a> and let us know what antivirus software you use. We'll contact them and try to straighten things out."
errorLaunchLibrary1 = "Failed to load an important file to start Minecraft.<br>To fix it, please navigate to this folder:<br>\""
errorLaunchLibrary2 = "\",<br>and delete the folder named \"config\".<br><br>If the error does not improve at the next startup, then in the the<br>\""
errorLaunchLibrary3 = "\"<br> folder, delete the \"libraries\" folder."
errorLaunchLibraryButton = "Open config folder"
errorLaunchLibraryButtonAlt = "Open libraries folder"
launched = "Done. Enjoy the server!"

[js.discord]
loading = "Loading game..."
playing = "Discovering the server!"
inMainMenu = "In the main menu..."
waiting = "Waiting for client..."
discord = "Discord"
website = "Website"

[js.shop]
close = "CLOSE SHOP"
open = "OPEN SHOP"
errorData = "Error loading data"
errorConsole = "See console (CTRL + Shift + I) for more errors."
loggedInAs = "Logged in as,"
accountInfo = "Account information"
playtime = "Your playtime"
hour = "hour"
minute = "minute"
registration = "Your registration"
balance = "Your balance"
profile = "Your profile"
settings = "Settings"
appearance = "Your appearance"
send = "Send PlayCoin"
profileFriends = "Online friends"
profileOnline = "Right now <span style=\"color: #8dbf42\">online</span>"
profileServer = "Server"
profilePlaytime = "Playtime"
skinHeader = "Skin upload"
skinDesc = "Stand out from the crowd and create your own look!"
skinSelect = "Select file"
skinUpload = "Upload"
ipProtHeader = "IP Protection"
ipProtDesc = "Protect your account's IP address so that only you can access the server with your account!"
ipProtCurrent = "Save your current IP address"
ipProtOther = "Save other IP address"
ipProtDelete = "Remove IP Protection"
ipAddress = "IP address"
ipSave = "Save"
aUpdate = "update"
aRemove = "remove"
aRankHeader = "Rank name"
aRankDesc = "Change your rank name, only you can see it!"
aPrefixSuffixHeader = "Prefix and Suffix"
aPrefixSuffixDesc = "Change your prefix and suffix, which everyone will see!"
aPrefix = "Prefix"
aSuffix = "Suffix"
aWelcomeMessageHeader = "Welcome message"
aWelcomeMessageDesc = "You can set a welcome message that everyone will see when you enter the server!"
aWelcomeMessageStart = "Beginning of welcome message"
aWelcomeMessageEnd = "End of welcome message"
aLeaveMessageHeader = "Leave message"
aLeaveMessageDesc = "You can set a leave message that everyone will see when you leave the server!"
aLeaveMessageStart = "Beginning of leave message"
aLeaveMessageEnd = "End of leave message"
aWelcomeSoundHeader = "Welcome sound"
aWelcomeSoundDesc = "You can set a welcome sound that everyone will hear when you enter the server!"
aWelcomeSoundSelect = "Select welcome sound"
aLeaveSoundHeader = "Leave sound"
aLeaveSoundDesc = "You can set a leabe sound that everyone will hear when you leave the server!"
aLeaveSoundSelect = "Select leave sound"
aChatHeader = "Chat color"
aChatDesc = "You can set a chat color that everyone will see when you write in the chat!"
aChatSelect = "Select chat color"
noPermission = "You do not have the right to change the appearance, this function is available for purchase at <a class=\"shopUrl\" href=\"https://playclan.hu/shop/kiegeszitok?id=global\" target=\"_blank\">the Shop</a>."
sendDesc = "The PlayCoin transfer cannot be withdrawn, so be careful to transfer to the right person!"
playername = "Playername"
sendCheck = "Check playername"
sendPC = "Send PlayCoin"
footer = "PlayClan Shop"
uploadSkinHeader = "Successful skin upload!"
uploadSkinDesc = "Enjoy your new skin!"
uploadSkinErrorHeader = "Error while uploading skin!"
uploadSkinErrorDesc = "Please select a valid skin file, and try again!"
ipProtSuccessHeader = "Successful IP Protection!"
ipProtSuccessDesc = "You can now access the server!"
ipProtErrorHeader = "Error while saving IP address!"
ipProtErrorDesc = "Please try again later!"
ipProtSuccessDeleteHeader = "Successful IP Protection removal!"
ipProtErrorDeleteHeader = "Error while removing IP Protection!"
aChatTest = "This is a test message!"
aSoundOff = "Off"
aSoundDoor = "Opening wooden door"
aSoundTrapdoor = "Opening wooden trap door"
aSoundXp = "Collecting XP"
aSoundLevelup = "Level up"
aSoundItem = "Item pickup"
aBlack = "Black - §0"
aDarkBlue = "Dark Blue - §1"
aDarkGreen = "Dark Green - §2"
aDarkAqua = "Dark Aqua - §3"
aDarkRed = "Dark Red - §4"
aDarkPurple = "Dark Purple - §5"
aGold = "Gold - §6"
aGray = "Gray - §7"
aDarkGray = "Dark Gray - §8"
aBlue = "Blue - §9"
aGreen = "Green - §a"
aAqua = "Aqua - §b"
aRed = "Red - §c"
aLightPurple = "Light Purple - §d"
aYellow = "Yellow - §e"
aWhite = "White - §f"
updateAppearanceSuccess = "Successful appearance update!"
updateAppearanceSuccessDesc = "Switch to another server to see the change!"
updateAppearanceError = "Error while updating appearance!"
updateAppearanceErrorCharDesc = "You have exceeded the character limit!<br>Maximum characters:"
updateAppearanceErrorOtherDesc = "Something went wrong while setting up the appearance!"
sendPCSuccess = "Successful PlayCoin transfer!"
sendPCSuccessDesc = "The other player got the PlayCoin!"
sendPCError = "PlayCoin transfer failed!"
sendPCErrorRateLimit = "You tried to refer too quickly, please wait a moment!"
sendPCErrorDesc = "You don't have enough PlayCoin balance!"
loginError = "Login error!"
loginErrorDesc = "To use this function, you must log in to your PlayClan account!"

[js.news]
loading = "Loading news"
comments = "comments"

[js.login]
errorTitle = "Unknown error during login"
errorDesc = "An unknown error has occurred. See console for details."
tryAgain = "Try again"

[js.settings]
errorHeader = "Something went wrong"
errorMicrosoftLogin = "Microsoft authentication failed. Please try again."
errorPlayClanLogin = "PlayClan authentication failed. Please try again."
errorMicrosftLogout = "Microsoft sign out failed. Please try again."
ok = "Ok"
accessDenied = "Access denied"
accessDeniedDesc = "Couldn't sign in to your Microsoft account because you canceled the sign in! Please try again!"
selectAccount = "Select account"
selectedAccount = "Selected account &#10004;"
logOutLastAccountHeader = "Attention!<br>This is your last account!"
logOutLastAccount = "You must be logged into at least one account to use the launcher. You will then need to log in again.<br><br>Are you sure you want to log in?"
logOutLastAccountConfirm = "Log out"
cancel = "Cancel"
playername = "Playername"
expiry = "Login is valid until"
logout = "Log out"
uuid = "UUID"
deleteModHeader = "Failed to delete mod:<br>"
deleteMod = "Make sure the file is not in use and try again."
errorModHeader = "Failed to switch<br>One or more mods"
latestVersion = "Latest version"
javaSelected = "Selected: Java"
javaRequired = "Required: Java"
javaNotFound = "Invalid Java access"
javaAvailable = "Available options for Java"
betaRelease = "Beta version"
stableRelease = "Stable version"
changelogError = "Failed to load changes."
new = "New"
stable = "Stable"
updateAvailable = "update available"
updateDarwin = "Download from GitHub <span style=\"font-size: 10px;color: gray;text-shadow: none !important;\">Close the launcher and run dmg to update.</span >"
download = "Download..."
noUpdate = "You are using the latest version!"
searchForUpdate = "Check for updates"
remove = "Remove"

[js.uibinder]
fatalStartupHeader = "Fatal Error: Failed to load distribution index"
fatalStartupContent = "Could not connect to our servers to download the distribution index. No local copy was available to load.<br><br>The distribution index is a core file that contains the latest server information. The launcher cannot launch without it. Make sure that connect to the internet and restart the app."
close = "Close"
loginErrorHeader = "Failed to update login information"
loginErrorContent = "We could not update the login for your <strong>{username}</strong> account. Please log in again."
loginErrorContentAnotherAccount = "We could not update the login for your <strong>{username}</strong> account. Please choose another account or log in again."
login = "Log in"
anotherAccount = "Select account"

[js.uicore]
console1 = "The console is dark and full of terrors."
console2 = "If you've been told to paste something here, you're being scammed."
console3 = "Unless you know exactly what you're doing, close this window."
searchForUpdates = "Check for updates..."
installNow = "Install now"
noUpdate = "Check for updates"

[js.dropinmodutil]
off = "Turned OFF"

[js.overlay]
dismiss = "Dismiss"
latestVersion = "Latest version"

[js.exit]
updateButton = "Update and close"
updateTitle = "Install update"
updateDetail = "After closing the application, an update will be installed, please wait 1 minute before restarting the application!"
stayButton = "Don't close"
closeButton = "Restart the app"
restartTitle = "Restart application"
restartDetail = "You need to restart the application to apply the language changes!"