[ejs.app]
loading = "Betöltés folyamatban..."

[ejs.landing]
shopButton = "PlayClan Shop"
updateAvailable = "Frissítés elérhető"
shopOpen = "SHOP MEGNYITÁSA"
playername = "Játékosnév"
edit = "Szerkesztés"
settings = "Beállítások"
server = "SZERVER"
offline = "NEM ELÉRHETŐ"
mojangStatus = "MOJANG STÁTUSZ"
mojangServices = "Szolgáltatások"
mojangNonEssential = "Nem lényeges"
news = "HÍREK"
start = "INDÍTÁS"
notSelected = "Nincs szerver kiválasztva"
wait = "Kérlek várj..."
newsLoading = "Hírek betöltése..."
newsFailed = "Hírek betöltése sikertelen"
retry = "Próbáld újra"
noNews = "Még nincs egy hírek se."

[ejs.login]
cancel = "Mégse"
title = "MINECRAFT BEJELENTKEZÉS"
invalidValue = "Helytelen érték"
email = "EMAIL VAGY JÁTÉKOSNÉV"
password = "JELSZÓ"
required = "Kötelező"
forgotPass = "Elfelejtett jelszó?"
rememberMe = "Emlékezz rám?"
login = "BEJELENTKEZÉS"
needAccount = "Szüksége van egy fiókra?"
privacy = "A jelszavát közvetlenül a Mojang-nak küldjük el, és soha nem tároljuk."

[ejs.loginOptions]
title = "Bejelentkezés"
playclan = "PlayClan fiók"
microsoft = "Microsoft fiók"
mojang = "Mojang fiók"
cancel = "Mégse"

[ejs.overlay]
serverHeader = "Elérhető verziók"
accountHeader = "Fiók kiválasztása"
cancel = "Mégse"
select = "Kiválasztás"

[ejs.settings.navbar]
header = "Beállítások"
account = "Fiók"
minecraft = "Minecraft"
mods = "Modok"
java = "Java"
launcher = "Launcher"
about = "Az alkalmazásról"
updates = "Frissítések"
done = "Kész"

[ejs.settings.account]
header = "Fiók beállítások"
desc = "Új fiók hozzáadása vagy meglévők kezelése."
playclan = "PlayClan"
playclanAdd = "+ PlayClan fiók hozzáadása"
microsoft = "Microsoft"
microsoftAdd = "+ Microsoft fiók hozzáadása"
mojang = "Mojang"
mojangAdd = "+ Mojang fiók hozzáadása"

[ejs.settings.minecraft]
header = "Minecraft beállítások"
desc = "A játék indításával kapcsolatos beállítások."
resolution = "Játék felbontása"
autoconnect = "Indításkor automatikusan csatlakozzon a szerverhez."
detach = "A játék leválasztva a launcherről."
detachDesc = "Ha a játék nincs leválasztva, a launcher bezárásával a játék is bezárul."

[ejs.settings.mods]
header = "Mod beállítások"
desc = "Modok engedélyezése vagy letiltása."
change = "Módosítás"
required = "Kötelező modok"
optional = "Opcionális modok"
mods = "Modok"
add = "+ Modok hozzáadása"
refresh = "(F5 az újratöltéshez)"
shaders = "Shadercsomagok"
shadersDesc = "Shadercsomagok engedélyezése vagy letiltása. Kérjük, vegye figyelembe, hogy a shaderek csak erős gépek esetén működnek zökkenőmentesen. Itt egyedi csomagokat adhat hozzá."
shadersSelect = "Shadercsomag választása"

[ejs.settings.java]
header = "Java beállítások"
desc = "Java konfiguráció kezelése (haladó)."
change = "Módosítás"
memory = "Memória"
memoryMax = "Maximum RAM"
memoryMin = "Minimum RAM"
memoryDesc = "Az ajánlott minimális RAM 3 gigabájt. A minimális és maximális értékek azonos értékre állítása csökkentheti az akadásokat."
memoryTotal = "Összes"
memoryAvaliable = "Elérhető"
executable = "Java futtatókörnyezet"
select = "Fájl kiválasztása"
execDesc = "A Java futtatható fájl érvényesítése a játék indítása előtt megtörténik."
execPath = "Az elérési útnak ezzel kell végződnie:"
other = "További JVM beállítások"
otherDesc = "A JVM számára megadható lehetőségek. <em>-Xms</em> és <em>-Xmx</em>-t már nem kell megadni."

[ejs.settings.launcher]
header = "Launcher beállítások"
desc = "A launcherrel kapcsolatos beállítások"
beta = "Béta frissítések engedélyezése."
betaDesc = "A béta verziók olyan új funkciókat tartalmaznak, amelyeket esetleg még nem teszteltek vagy integráltak teljesen.<br>Ez mindig igaz, ha béta verziót használ."
discord = "Discord Rich Presence engedélyezése."
discordDesc = "A Discord Rich Presence engedélyezésével a Discord profilodon megoszthatod, hogy éppen mivel játszol."
hide = "Launcher automatikus eltüntetése."
hideDesc = "A Launcher eltüntetésének engedélyezésével arra az időszakra eltűnik, amíg fut a Minecraft."
ipProtection = "Automatikus IP levédés engedélyezése."
ipProtectionDesc = "Az automatikus IP levédés engedélyezésével, a fiókod automatikusan le lesz védve az IP címedre, amikor elindítod a Minecraft-ot. <small>(Ez a funkció csak akkor működik, ha a PlayClan fiókoddal indítod el a Minecraft-ot.)</small>"
folder = "Adatok mappa"
folderChoose = "Mappa kiválasztása"
folderDesc = "Minden játékfájl és helyi Java telepítés ebben a mappában tárolódik.<br>A képernyőképek és a világmentések a megfelelő szerverkonfiguráció mappájában tárolódnak."

[ejs.settings.about]
header = "Az alkalmazásról"
desc = "Az aktuális verzióra vonatkozó információk és változtatásnapló megtekintése."
title = "PlayClan Launcher"
source = "Forráskód (GitHub)"
originalSource = "Eredeti forráskód (GitHub)"
help = "Segítség kérése"
devtools = "DevTools Konzol"
changelog = "Változtatásnapló"
changes = "Változtatások"
noChanges = "Nincs változtatás"
changesGithub = "Változtatások megtekintése GitHub-on"

[ejs.settings.updates]
header = "Launcher frissítések"
desc = "Töltse le, telepítse és tekintse át a launcher frissítéseit."
uptodate = "A legújabb verziót használja!"
search = "Frissítések keresése"
whatsnew = "Mi az újdonság?"
changes = "Frissítési változtatásnapló"
noChanges = "Nincs változtatás"

[ejs.waiting]
microsoft = "Várakozás a Microsoft válaszára..."
playclan = "Várakozás a PlayClan válaszára..."

[ejs.welcome]
header = "ÜDVÖZÖL A PLAYCLAN LAUNCHER!"
desc = "Ezzel a launcherrel az a célunk hogy egy jobb játékélményt nyújtsunk mindenkinek, aki használja."
cta = "Csak egy pár kattintásra vagy a felfedezéstől!"
button = "TOVÁBB"

[js.landing]
pleaseWait = "Betöltés folyamatban..."
errorStartupTitle = "Elindítási hiba"
errorConsole = "Lásd a konzolt (CTRL + Shift + i) további hibákért."
noAccount = "Nincs fiók kiválasztva"
noServer = "Nincs szerver kiválasztva"
loading = "Betöltés..."
server = "SZERVER"
offline = "OFFLINE"
players = "JÁTÉKOSOK"
checkingJava = "Java ellenőrzése..."
javaNotFoundTitle = "Nem található kompatibilis<br>Java telepítés"
javaNotFoundContent1 = "A PlayClan-hoz való csatlakozáshoz 64 bites Java"
javaNotFoundContent2 = "telepítésre van szüksége. Szeretné, hogy telepítsük?"
javaNotFoundButton = "Java telepítése"
javaNotFoundButtonAlt = "Manuális telepítés"
downloadJava = "Java letöltése..."
errorJavaTitle = "Hiba a Java letöltése közben"
javaManualTitle = "Az indításhoz<br>Java szükséges"
javaManualContent1 = "Egy érvényes x64-es Java"
javaManualContent2 = "telepítése az indításához szükséges.<br><br>Kérjük, tekintse meg a <a href=\"https://github.com/PlayClan/PCLauncher/wiki/Java-Management#manually-installing-a-valid-version-of-java\">Java kezelési útmutató</a>-t a Java manuális telepítéséhez."
javaManualButton = "Megértettem"
javaManualButtonAlt = "Vissza"
extractingJava = "Java kicsomagolása..."
javaComplete = "Java telepítve!"
loadingInfo = "Információk betöltése..."
fatal = "Végzetes hiba"
verifying = "Kérem várjon..."
validating = "Fájlok ellenőrzése..."
downloading = "Fájlok letöltése..."
errorValidate = "Hiba a fájlok ellenőrzése során"
errorDownload = "Hiba a fájlok letöltése során"
finalizing = "Befejezés..."
launching = "Játék elindítása..."
errorLaunch = "Hiba az indítás során"
errorLaunchWrapper = "A fő fájl, a LaunchWrapper letöltése nem sikerült megfelelően. Ezért játék nem indul el.<br><br>A probléma megoldásához ideiglenesen kapcsolja ki a víruskereső szoftvert, és indítsa újra a játékot.<br><br>Ha van ideje kérjük <a href=\"https://dc.playclan.hu/\">jelentse be a hibát</a> és tudassa velünk, milyen víruskereső szoftvert használ. Felvesszük veled a kapcsolatot, és megpróbáljuk megoldani a problémát."
errorLaunchLibrary1 = "Nem sikerült betölteni egy fontos fájlt a Minecraft elindításához.<br>A javításhoz kérlek navigálj el ebbe a mappába:<br>\""
errorLaunchLibrary2 = "\",<br>és töröld ki a \"config\" nevezetű mappát.<br><br>Ha a hiba a következő indításnál sem javul meg, akkor a<br>\""
errorLaunchLibrary3 = "\"<br>mappában a \"libraries\" mappát töröld ki."
errorLaunchLibraryButton = "Config mappa megnyitása"
errorLaunchLibraryButtonAlt = "Libraries mappa megnyitása"
launched = "Kész. Jó játékot!"

[js.discord]
loading = "Játék betöltése..."
playing = "Felfedezi a szervert!"
inMainMenu = "Főképernyőn..."
waiting = "Várakozás a kliensre..."
discord = "Discord"
website = "Weboldal"

[js.shop]
close = "SHOP BEZÁRÁSA"
open = "SHOP MEGNYITÁSA"
errorData = "Hiba az adatok betöltése során"
errorConsole = "Lásd a konzolt (CTRL + Shift + I) további hibákért."
loggedInAs = "Bejelentkezve mint,"
accountInfo = "Fiók információk"
playtime = "Játékidőd"
hour = "óra"
minute = "perc"
registration = "Regisztrációd"
balance = "Egyenleged"
profile = "Profilod"
settings = "Beállítások"
appearance = "Kinézeted"
send = "PlayCoin utalás"
profileFriends = "Elérhető barátok"
profileOnline = "Jelenleg <span style=\"color: #8dbf42\">online</span>"
profileServer = "Szerver"
profilePlaytime = "Játékidő"
skinHeader = "Skin feltöltés"
skinDesc = "Tűnj ki a tömegből, és állítsd be magadnak saját kinézetet!"
skinSelect = "Fájl kiválasztása"
skinUpload = "Feltöltés"
ipProtHeader = "IP Levédés"
ipProtDesc = "Védd le a fiókod IP címed, hogy csak te tudj felmenni a szerverre a fiókoddal!"
ipProtCurrent = "Levédés a jelenlegi IP címmel"
ipProtOther = "Levédés más IP címmel"
ipProtDelete = "Levédés törlése"
ipAddress = "IP cím"
ipSave = "Levédés"
aUpdate = "frissítése"
aRemove = "törlése"
aRankHeader = "Rang neved"
aRankDesc = "Változtasd meg a rang nevedet, ezt csak te látod!"
aPrefixSuffixHeader = "Prefix és Suffix"
aPrefixSuffixDesc = "Változtasd meg a prefixedet és suffixodat, amelyet mindenki lát majd!"
aPrefix = "Prefix"
aSuffix = "Suffix"
aWelcomeMessageHeader = "Üdvözlő üzeneted"
aWelcomeMessageDesc = "Üdvözlő üzenetet állíthatsz be, amit mindenki látni fog, amikor belépsz a szerverre!"
aWelcomeMessageStart = "Üdvözlő üzeneted eleje"
aWelcomeMessageEnd = "Üdvözlő üzeneted vége"
aLeaveMessageHeader = "Kilépő üzeneted"
aLeaveMessageDesc = "Kilépő üzenetet állíthatsz be, amit mindenki látni fog, amikor kilépsz a szerverről!"
aLeaveMessageStart = "Kilépő üzeneted eleje"
aLeaveMessageEnd = "Kilépő üzeneted vége"
aWelcomeSoundHeader = "Üdvözlő hangod"
aWelcomeSoundDesc = "Üdvözlő hangot állíthatsz be, amit mindenki hallani fog, amikor belépsz a szerverre!"
aWelcomeSoundSelect = "Üdvözlőhang kiválasztása"
aLeaveSoundHeader = "Kilépő hangod"
aLeaveSoundDesc = "Kilépő hangot állíthatsz be, amit mindenki hallani fog, amikor kilépsz a szerverről!"
aLeaveSoundSelect = "Kilépőhang kiválasztása"
aChatHeader = "Chat színed"
aChatDesc = "Chat színt állíthatsz be, amit mindenki látni fog, amikor írsz a chatbe!"
aChatSelect = "Chat szín kiválasztása"
noPermission = "Nincs jogod kinézetet változtatni, ez a funkció elérhető megvásárlásra a <a class=\"shopUrl\" href=\"https://playclan.hu/shop/kiegeszitok?id=global\" target=\"_blank\">Shop</a>-ban."
sendDesc = "A PlayCoin utalás vissza nem vonható, szóval jól figyelj, hogy jó személynek utalj!"
playername = "Játékosnév"
sendCheck = "Játékosnév ellenőrzése"
sendPC = "PlayCoin átutalása"
footer = "PlayClan Shop"
uploadSkinHeader = "Skin feltöltése sikeres!"
uploadSkinDesc = "Élvezd az új skinedet!"
uploadSkinErrorHeader = "A fájl feltöltése sikertelen volt!"
uploadSkinErrorDesc = "Kérlek válassz ki egy fájlt, a feltöltéshez!"
ipProtSuccessHeader = "Sikeres IP levédés!"
ipProtSuccessDesc = "Mostmár felléphetsz a szerverre!"
ipProtErrorHeader = "Sikertelem IP levédés!"
ipProtErrorDesc = "Kérlek próbáld újra!"
ipProtSuccessDeleteHeader = "Sikeres IP levédés törlés!"
ipProtErrorDeleteHeader = "Sikertelen IP levédés törlés!"
aChatTest = "Ez egy teszt szöveg!"
aSoundOff = "Kikapcsolva"
aSoundDoor = "Faajtó kinyitás"
aSoundTrapdoor = "Facsapóajtó kinyitás"
aSoundXp = "XP begyűjtés"
aSoundLevelup = "Szint felfejlődés"
aSoundItem = "Tárgy felvétel"
aBlack = "Fekete - §0"
aDarkBlue = "Sötétkék - §1"
aDarkGreen = "Sötétzöld - §2"
aDarkAqua = "Sötétkékzöld - §3"
aDarkRed = "Sötétvörös - §4"
aDarkPurple = "Sötétlila - §5"
aGold = "Arany - §6"
aGray = "Szürke - §7"
aDarkGray = "Sötétszürke - §8"
aBlue = "Kék - §9"
aGreen = "Zöld - §a"
aAqua = "Kékzöld - §b"
aRed = "Vörös - §c"
aLightPurple = "Lila - §d"
aYellow = "Sárga - §e"
aWhite = "Fehér - §f"
updateAppearanceSuccess = "Sikeres kinézet frissítés!"
updateAppearanceSuccessDesc = "Lépj át egy másik szerverre, hogy lásd a változást!"
updateAppearanceError = "Sikertelen kinézet frissítés!"
updateAppearanceErrorCharDesc = "Meghaladtad a karakterkorlátot!<br>Maximális karakterek:"
updateAppearanceErrorOtherDesc = "Valami hiba történt a kinézet beállítása közben!"
sendPCSuccess = "Sikeres PlayCoin utalás!"
sendPCSuccessDesc = "A másik játékos megkapta a PlayCoin-t!"
sendPCError = "Sikertelen PlayCoin utalás!"
sendPCErrorRateLimit = "Túl gyorsan próbáltál utalni, kérjek várj egy kicsit!"
sendPCErrorDesc = "Nincs elég PlayCoin egyenleged!"
loginError = "Bejelentkezési hiba!"
loginErrorDesc = "Ehhez a funkció használatához a PlayClan fiókodba kell bejelentkezned!"

[js.news]
loading = "Hírek betöltése"
comments = "komment"

[js.login]
errorTitle = "Ismeretlen hiba a bejelentkezés során"
errorDesc = "Ismeretlen hiba lépett fel. A részletekért lásd a konzolt."
tryAgain = "Próbáld újra"

[js.settings]
errorHeader = "Valami hiba történt"
errorMicrosoftLogin = "A Microsoft hitelesítés sikertelen. Kérlek próbáld újra."
errorPlayClanLogin = "A PlayClan hitelesítés sikertelen. Kérlek próbáld újra."
errorMicrosftLogout = "A Microsoft kijelentkezés nem sikerült. Kérlek próbáld újra."
ok = "Ok"
accessDenied = "Hozzáférés megtagadva"
accessDeniedDesc = "Nem sikerült bejelentkezni a Microsoft fiókodba, mivel megszakítottad a bejelentkezést! Kérlek próbáld újra!"
selectAccount = "Fiók kiválasztása"
selectedAccount = "Kiválasztott fiók &#10004;"
logOutLastAccountHeader = "Figyelem!<br>Ez az utolsó fiókod!"
logOutLastAccount = "A launcher használatához legalább egy fiókba be kell jelentkeznie. Ezután újra be kell jelentkeznie.<br><br>Biztosan ki szeretne jelentkezni?"
logOutLastAccountConfirm = "Biztos vagyok benne"
cancel = "Mégsem"
playername = "Játékosnév"
expiry = "Bejelentkezés érvényes"
logout = "Kijelentkezés"
uuid = "UUID"
deleteModHeader = "Nem sikerült törölni a modot:<br>"
deleteMod = "Győződjön meg arról, hogy a fájl nincs használatban, és próbálja újra."
errorModHeader = "Nem sikerült a váltás<br>Egy vagy több modnál"
latesVersion = "Legújabb verzió"
javaSelected = "Kiválasztva: Java"
javaRequired = "Szükséges: Java"
javaNotFound = "Érvénytelen Java elérés"
javaAvailable = "Elérhető lehetőségek a Java"
betaRelease = "Béta verzió"
stableRelease = "Stabil verzió"
changelogError = "Nem sikerült betölteni a változtatásokat."
new = "Új"
beta = "béta"
updateAvailable = "frissítés elérhető"
updateDarwin = "Töltsd le a GitHubról <span style=\"font-size: 10px;color: gray;text-shadow: none !important;\">Zárja be a launcher-t, és futtassa a dmg-t a frissítéshez.</span>"
download = "Letöltés..."
noUpdate = "A legújabb verziót használod!"
searchForUpdate = "Frissítések keresése"
remove = "Eltávolítás"

[js.uibinder]
fatalStartupHeader = "Végzetes hiba: Nem sikerült betölteni az terjesztési indexet"
fatalStartupContent = "Nem sikerült kapcsolatot létesíteni a szervereinkkel a terjesztési index letöltéséhez. Nem volt elérhető betölthető helyi példány.<br><br>A terjesztési index egy alapvető fájl, amely a legfrissebb szerverinformációkat tartalmazza. A launcher nem tud elindulni nélküle. Győződjön meg arról, hogy csatlakozik az internethez, és indítsa újra az alkalmazást."
close = "Bezárás"
loginErrorHeader = "Nem sikerült a bejelentkezési adatok frissítése"
loginErrorContent = "Nem tudtuk frissíteni a bejelentkezést <strong>{username}</strong> fiókjának. Kérlek jelentkezz be újra."
loginErrorContentAnotherAccount = "Nem tudtuk frissíteni a bejelentkezést <strong>{username}</strong> fiókjának. Kérlek válassz másik fiókot vagy jelentkezz be újra."
login = "Bejelentkezés"
anotherAccount = "Fiók választása"

[js.uicore]
console1 = "A konzol sötét és tele van rossz dolgokkal :O"
console2 = "Ha azt mondták neked, hogy illessz be valamit, akkor éppen átvernek."
console3 = "Hacsak nem tudod pontosan, hogy mit csinálsz, zárd be ezt az ablakot."
searchForUpdates = "Frissítések keresése..."
installNow = "Telepítés most"
noUpdate = "Frissítések keresése"

[js.dropinmodutil]
off = "Kikapcsolva"

[js.overlay]
dismiss = "Elvetés"